### ISSUE TITLE
Vue Axios

### ISSUE THREAD

**Issue by Diddyy** [vedmant/jogging-time#2]
Heya!

Know you already plan to add axios, just wondering if you have plans to add it anytime soon? :)

Have looked at doing it myself but can't seem to work it out at the moment.
Love the project though!

Thanks :)

**Comment by vedmant** [comment]
Hey, yes, I'm planning to switch to Axios but don't have much free time right now to do so. Maybe next weeks I'll dedicate some time for it.

**Comment by vedmant** [comment]
Hey, I just edited app to use axios, check master branch.
